version: 2.1

orbs:
  python: circleci/python@1.3.3
  gcp-gcr: circleci/gcp-gcr@0.13.0

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - gcp-gcr/build-and-push-image:
          image: devops-bookstore-api
          tag: '1.$CIRCLE_BUILD_NUM'
          registry-url: eu.gcr.io
          requires:
            - "python/test"
